// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest.Models
{
    using System.Linq;

    /// <summary>
    /// The schema of the asset
    /// </summary>
    [Microsoft.Rest.Serialization.JsonTransformation]
    public partial class FunctionSchema
    {
        /// <summary>
        /// Initializes a new instance of the FunctionSchema class.
        /// </summary>
        public FunctionSchema() { }

        /// <summary>
        /// Initializes a new instance of the FunctionSchema class.
        /// </summary>
        /// <param name="parameterSet">parameterSet property</param>
        /// <param name="resultSet">resultSet property</param>
        /// <param name="fromSourceSystem">fromSourceSystem property</param>
        public FunctionSchema(FunctionSchemaBodyParameterSet parameterSet, FunctionSchemaBodyResultSet resultSet, bool fromSourceSystem, System.Collections.Generic.IList<RolesItem> roles = default(System.Collections.Generic.IList<RolesItem>))
        {
            ParameterSet = parameterSet;
            ResultSet = resultSet;
            FromSourceSystem = fromSourceSystem;
            Roles = roles;
        }

        /// <summary>
        /// Gets or sets parameterSet property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.parameterSet")]
        public FunctionSchemaBodyParameterSet ParameterSet { get; set; }

        /// <summary>
        /// Gets or sets resultSet property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.resultSet")]
        public FunctionSchemaBodyResultSet ResultSet { get; set; }

        /// <summary>
        /// Gets or sets fromSourceSystem property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.fromSourceSystem")]
        public bool FromSourceSystem { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "roles")]
        public System.Collections.Generic.IList<RolesItem> Roles { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ParameterSet == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ParameterSet");
            }
            if (ResultSet == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "ResultSet");
            }
            if (this.Roles != null)
            {
                foreach (var element in this.Roles)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
