// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest.Models
{
    using System.Linq;

    /// <summary>
    /// ResultSet format
    /// </summary>
    public partial class ResultSet
    {
        /// <summary>
        /// Initializes a new instance of the ResultSet class.
        /// </summary>
        public ResultSet() { }

        /// <summary>
        /// Initializes a new instance of the ResultSet class.
        /// </summary>
        /// <param name="columns">columns property</param>
        public ResultSet(System.Collections.Generic.IList<Column> columns)
        {
            Columns = columns;
        }

        /// <summary>
        /// Gets or sets columns property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "columns")]
        public System.Collections.Generic.IList<Column> Columns { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Columns == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Columns");
            }
            if (this.Columns != null)
            {
                foreach (var element in this.Columns)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
