// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest.Models
{
    using System.Linq;

    /// <summary>
    /// RolesItem format
    /// </summary>
    public partial class RolesItem
    {
        /// <summary>
        /// Initializes a new instance of the RolesItem class.
        /// </summary>
        public RolesItem() { }

        /// <summary>
        /// Initializes a new instance of the RolesItem class.
        /// </summary>
        /// <param name="role">Role format. Possible values include: 'Owner',
        /// 'Contributor', 'Administrator'</param>
        /// <param name="members">List of members</param>
        public RolesItem(Role role, System.Collections.Generic.IList<MembersItem> members)
        {
            Role = role;
            Members = members;
        }

        /// <summary>
        /// Gets or sets role format. Possible values include: 'Owner',
        /// 'Contributor', 'Administrator'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "role")]
        public Role Role { get; set; }

        /// <summary>
        /// Gets or sets list of members
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "members")]
        public System.Collections.Generic.IList<MembersItem> Members { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Members == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Members");
            }
            if (this.Members != null)
            {
                foreach (var element in this.Members)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
