// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest
{
    using System.Threading.Tasks;
   using Microsoft.Rest.Azure;
   using Models;

    /// <summary>
    /// Extension methods for ContainerOperations.
    /// </summary>
    public static partial class ContainerOperationsExtensions
    {
            /// <summary>
            /// Register Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='container'>
            /// Register Container
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerRegisterHeaders Register(this IContainerOperations operations, Container container, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).RegisterAsync(container, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Register Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='container'>
            /// Register Container
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerRegisterHeaders> RegisterAsync(this IContainerOperations operations, Container container, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RegisterWithHttpMessagesAsync(container, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerGet Get(this IContainerOperations operations, string viewItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetAsync(viewItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerGet> GetAsync(this IContainerOperations operations, string viewItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(viewItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteHeaders Delete(this IContainerOperations operations, string viewItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteAsync(viewItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete Container
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteHeaders> DeleteAsync(this IContainerOperations operations, string viewItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteWithHttpMessagesAsync(viewItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='description'>
            /// description payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddDescriptionHeaders AddDescription(this IContainerOperations operations, string viewItemId, Description description, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddDescriptionAsync(viewItemId, description, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='description'>
            /// description payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddDescriptionHeaders> AddDescriptionAsync(this IContainerOperations operations, string viewItemId, Description description, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddDescriptionWithHttpMessagesAsync(viewItemId, description, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='expert'>
            /// expert payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddExpertHeaders AddExpert(this IContainerOperations operations, string viewItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddExpertAsync(viewItemId, expert, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='expert'>
            /// expert payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddExpertHeaders> AddExpertAsync(this IContainerOperations operations, string viewItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddExpertWithHttpMessagesAsync(viewItemId, expert, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='accessInstruction'>
            /// accessinstruction payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddAccessInstructionHeaders AddAccessInstruction(this IContainerOperations operations, string viewItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddAccessInstructionAsync(viewItemId, accessInstruction, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='accessInstruction'>
            /// accessinstruction payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddAccessInstructionHeaders> AddAccessInstructionAsync(this IContainerOperations operations, string viewItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddAccessInstructionWithHttpMessagesAsync(viewItemId, accessInstruction, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='documentation'>
            /// documentation payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddDocumentationHeaders AddDocumentation(this IContainerOperations operations, string viewItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddDocumentationAsync(viewItemId, documentation, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='documentation'>
            /// documentation payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddDocumentationHeaders> AddDocumentationAsync(this IContainerOperations operations, string viewItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddDocumentationWithHttpMessagesAsync(viewItemId, documentation, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='friendlyName'>
            /// friendlyname payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddFriendlyNameHeaders AddFriendlyName(this IContainerOperations operations, string viewItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddFriendlyNameAsync(viewItemId, friendlyName, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='friendlyName'>
            /// friendlyname payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddFriendlyNameHeaders> AddFriendlyNameAsync(this IContainerOperations operations, string viewItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddFriendlyNameWithHttpMessagesAsync(viewItemId, friendlyName, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='tag'>
            /// tag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddTagHeaders AddTag(this IContainerOperations operations, string viewItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddTagAsync(viewItemId, tag, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='tag'>
            /// tag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddTagHeaders> AddTagAsync(this IContainerOperations operations, string viewItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddTagWithHttpMessagesAsync(viewItemId, tag, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Add TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='termTag'>
            /// termtag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ContainerAddTermTagHeaders AddTermTag(this IContainerOperations operations, string viewItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).AddTermTagAsync(viewItemId, termTag, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Add TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='termTag'>
            /// termtag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerAddTermTagHeaders> AddTermTagAsync(this IContainerOperations operations, string viewItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.AddTermTagWithHttpMessagesAsync(viewItemId, termTag, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='description'>
            /// description payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateDescriptionHeaders UpdateDescription(this IContainerOperations operations, string viewItemId, string annotationItemId, Description description, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateDescriptionAsync(viewItemId, annotationItemId, description, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='description'>
            /// description payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateDescriptionHeaders> UpdateDescriptionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Description description, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateDescriptionWithHttpMessagesAsync(viewItemId, annotationItemId, description, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static DescriptionGet GetDescription(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetDescriptionAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<DescriptionGet> GetDescriptionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetDescriptionWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteDescriptionHeaders DeleteDescription(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteDescriptionAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete Description
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteDescriptionHeaders> DeleteDescriptionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteDescriptionWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='expert'>
            /// expert payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateExpertHeaders UpdateExpert(this IContainerOperations operations, string viewItemId, string annotationItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateExpertAsync(viewItemId, annotationItemId, expert, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='expert'>
            /// expert payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateExpertHeaders> UpdateExpertAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateExpertWithHttpMessagesAsync(viewItemId, annotationItemId, expert, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static ExpertGet GetExpert(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetExpertAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ExpertGet> GetExpertAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetExpertWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteExpertHeaders DeleteExpert(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteExpertAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete Expert
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteExpertHeaders> DeleteExpertAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteExpertWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='accessInstruction'>
            /// accessinstruction payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateAccessInstructionHeaders UpdateAccessInstruction(this IContainerOperations operations, string viewItemId, string annotationItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateAccessInstructionAsync(viewItemId, annotationItemId, accessInstruction, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='accessInstruction'>
            /// accessinstruction payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateAccessInstructionHeaders> UpdateAccessInstructionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateAccessInstructionWithHttpMessagesAsync(viewItemId, annotationItemId, accessInstruction, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static AccessInstructionGet GetAccessInstruction(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetAccessInstructionAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<AccessInstructionGet> GetAccessInstructionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetAccessInstructionWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteAccessInstructionHeaders DeleteAccessInstruction(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteAccessInstructionAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete AccessInstruction
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteAccessInstructionHeaders> DeleteAccessInstructionAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteAccessInstructionWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='documentation'>
            /// documentation payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateDocumentationHeaders UpdateDocumentation(this IContainerOperations operations, string viewItemId, string annotationItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateDocumentationAsync(viewItemId, annotationItemId, documentation, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='documentation'>
            /// documentation payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateDocumentationHeaders> UpdateDocumentationAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateDocumentationWithHttpMessagesAsync(viewItemId, annotationItemId, documentation, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static DocumentationGet GetDocumentation(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetDocumentationAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<DocumentationGet> GetDocumentationAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetDocumentationWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteDocumentationHeaders DeleteDocumentation(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteDocumentationAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete Documentation
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteDocumentationHeaders> DeleteDocumentationAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteDocumentationWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='friendlyName'>
            /// friendlyname payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateFriendlyNameHeaders UpdateFriendlyName(this IContainerOperations operations, string viewItemId, string annotationItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateFriendlyNameAsync(viewItemId, annotationItemId, friendlyName, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='friendlyName'>
            /// friendlyname payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateFriendlyNameHeaders> UpdateFriendlyNameAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateFriendlyNameWithHttpMessagesAsync(viewItemId, annotationItemId, friendlyName, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static FriendlyNameGet GetFriendlyName(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetFriendlyNameAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<FriendlyNameGet> GetFriendlyNameAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetFriendlyNameWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteFriendlyNameHeaders DeleteFriendlyName(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteFriendlyNameAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete FriendlyName
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteFriendlyNameHeaders> DeleteFriendlyNameAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteFriendlyNameWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='tag'>
            /// tag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateTagHeaders UpdateTag(this IContainerOperations operations, string viewItemId, string annotationItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateTagAsync(viewItemId, annotationItemId, tag, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='tag'>
            /// tag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateTagHeaders> UpdateTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateTagWithHttpMessagesAsync(viewItemId, annotationItemId, tag, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static TagGet GetTag(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetTagAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<TagGet> GetTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetTagWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteTagHeaders DeleteTag(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteTagAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete Tag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteTagHeaders> DeleteTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteTagWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Update TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='termTag'>
            /// termtag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerUpdateTermTagHeaders UpdateTermTag(this IContainerOperations operations, string viewItemId, string annotationItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).UpdateTermTagAsync(viewItemId, annotationItemId, termTag, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='termTag'>
            /// termtag payload
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerUpdateTermTagHeaders> UpdateTermTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdateTermTagWithHttpMessagesAsync(viewItemId, annotationItemId, termTag, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

            /// <summary>
            /// Get TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            public static TermTagGet GetTermTag(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).GetTermTagAsync(viewItemId, annotationItemId, settings, xMsClientRequestId), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<TermTagGet> GetTermTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.GetTermTagWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            public static ContainerDeleteTermTagHeaders DeleteTermTag(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string))
            {
                return System.Threading.Tasks.Task.Factory.StartNew(s => ((IContainerOperations)s).DeleteTermTagAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch), operations, System.Threading.CancellationToken.None, System.Threading.Tasks.TaskCreationOptions.None, System.Threading.Tasks.TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete TermTag
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewItemId'>
            /// View item Id
            /// </param>
            /// <param name='annotationItemId'>
            /// Annotation item Id
            /// </param>
            /// <param name='settings'>
            /// Additional parameters for the operation
            /// </param>
            /// <param name='xMsClientRequestId'>
            /// x-ms-client-request-id
            /// </param>
            /// <param name='ifMatch'>
            /// If-Match
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<ContainerDeleteTermTagHeaders> DeleteTermTagAsync(this IContainerOperations operations, string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.DeleteTermTagWithHttpMessagesAsync(viewItemId, annotationItemId, settings, xMsClientRequestId, ifMatch, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Headers;
                }
            }

    }
}
