// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest
{
    using Microsoft.Rest.Azure;
    using Models;

    /// <summary>
    /// MeasureOperations operations.
    /// </summary>
    public partial interface IMeasureOperations
    {
        /// <summary>
        /// Register Measure
        /// </summary>
        /// <param name='measure'>
        /// Register Measure
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureRegisterHeaders>> RegisterWithHttpMessagesAsync(Measure measure, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Measure
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<MeasureGet,MeasureGetHeaders>> GetWithHttpMessagesAsync(string viewItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Measure
        /// </summary>
        /// <param name='viewItemId'>
        /// View item id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteHeaders>> DeleteWithHttpMessagesAsync(string viewItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add Description
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='description'>
        /// description payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddDescriptionHeaders>> AddDescriptionWithHttpMessagesAsync(string viewItemId, Description description, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add Expert
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='expert'>
        /// expert payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddExpertHeaders>> AddExpertWithHttpMessagesAsync(string viewItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add AccessInstruction
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='accessInstruction'>
        /// accessinstruction payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddAccessInstructionHeaders>> AddAccessInstructionWithHttpMessagesAsync(string viewItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add Documentation
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='documentation'>
        /// documentation payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddDocumentationHeaders>> AddDocumentationWithHttpMessagesAsync(string viewItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add FriendlyName
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='friendlyName'>
        /// friendlyname payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddFriendlyNameHeaders>> AddFriendlyNameWithHttpMessagesAsync(string viewItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add Tag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='tag'>
        /// tag payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddTagHeaders>> AddTagWithHttpMessagesAsync(string viewItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Add TermTag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='termTag'>
        /// termtag payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureAddTermTagHeaders>> AddTermTagWithHttpMessagesAsync(string viewItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Description
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='description'>
        /// description payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateDescriptionHeaders>> UpdateDescriptionWithHttpMessagesAsync(string viewItemId, string annotationItemId, Description description, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Description
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<DescriptionGet,MeasureGetDescriptionHeaders>> GetDescriptionWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Description
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteDescriptionHeaders>> DeleteDescriptionWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Expert
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='expert'>
        /// expert payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateExpertHeaders>> UpdateExpertWithHttpMessagesAsync(string viewItemId, string annotationItemId, Expert expert, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Expert
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<ExpertGet,MeasureGetExpertHeaders>> GetExpertWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Expert
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteExpertHeaders>> DeleteExpertWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update AccessInstruction
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='accessInstruction'>
        /// accessinstruction payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateAccessInstructionHeaders>> UpdateAccessInstructionWithHttpMessagesAsync(string viewItemId, string annotationItemId, AccessInstruction accessInstruction, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get AccessInstruction
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<AccessInstructionGet,MeasureGetAccessInstructionHeaders>> GetAccessInstructionWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete AccessInstruction
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteAccessInstructionHeaders>> DeleteAccessInstructionWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Documentation
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='documentation'>
        /// documentation payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateDocumentationHeaders>> UpdateDocumentationWithHttpMessagesAsync(string viewItemId, string annotationItemId, Documentation documentation, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Documentation
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<DocumentationGet,MeasureGetDocumentationHeaders>> GetDocumentationWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Documentation
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteDocumentationHeaders>> DeleteDocumentationWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update FriendlyName
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='friendlyName'>
        /// friendlyname payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateFriendlyNameHeaders>> UpdateFriendlyNameWithHttpMessagesAsync(string viewItemId, string annotationItemId, FriendlyName friendlyName, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get FriendlyName
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<FriendlyNameGet,MeasureGetFriendlyNameHeaders>> GetFriendlyNameWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete FriendlyName
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteFriendlyNameHeaders>> DeleteFriendlyNameWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Tag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='tag'>
        /// tag payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateTagHeaders>> UpdateTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, Tag tag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Tag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<TagGet,MeasureGetTagHeaders>> GetTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Tag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteTagHeaders>> DeleteTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update TermTag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='termTag'>
        /// termtag payload
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureUpdateTermTagHeaders>> UpdateTermTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, TermTag termTag, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get TermTag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationResponse<TermTagGet,MeasureGetTermTagHeaders>> GetTermTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete TermTag
        /// </summary>
        /// <param name='viewItemId'>
        /// View item Id
        /// </param>
        /// <param name='annotationItemId'>
        /// Annotation item Id
        /// </param>
        /// <param name='settings'>
        /// Additional parameters for the operation
        /// </param>
        /// <param name='xMsClientRequestId'>
        /// x-ms-client-request-id
        /// </param>
        /// <param name='ifMatch'>
        /// If-Match
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<Microsoft.Rest.Azure.AzureOperationHeaderResponse<MeasureDeleteTermTagHeaders>> DeleteTermTagWithHttpMessagesAsync(string viewItemId, string annotationItemId, Settings settings, string xMsClientRequestId = default(string), string ifMatch = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
