// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest.Models
{
    using System.Linq;

    /// <summary>
    /// Column format
    /// </summary>
    public partial class Column
    {
        /// <summary>
        /// Initializes a new instance of the Column class.
        /// </summary>
        public Column() { }

        /// <summary>
        /// Initializes a new instance of the Column class.
        /// </summary>
        /// <param name="name">name property</param>
        /// <param name="type">type property</param>
        /// <param name="maxLength">maxLength property</param>
        /// <param name="precision">precision property</param>
        /// <param name="isNullable">isNullable property</param>
        /// <param name="expression">expression property</param>
        public Column(string name, string type, int? maxLength = default(int?), string precision = default(string), bool? isNullable = default(bool?), string expression = default(string))
        {
            Name = name;
            Type = type;
            MaxLength = maxLength;
            Precision = precision;
            IsNullable = isNullable;
            Expression = expression;
        }

        /// <summary>
        /// Gets or sets name property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets type property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets maxLength property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "maxLength")]
        public int? MaxLength { get; set; }

        /// <summary>
        /// Gets or sets precision property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "precision")]
        public string Precision { get; set; }

        /// <summary>
        /// Gets or sets isNullable property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "isNullable")]
        public bool? IsNullable { get; set; }

        /// <summary>
        /// Gets or sets expression property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "expression")]
        public string Expression { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Name");
            }
            if (Type == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
