// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Microsoft.Azure.DataCatalog.Rest.Models
{
    using System.Linq;

    /// <summary>
    /// Data profiles of the table asset
    /// </summary>
    [Microsoft.Rest.Serialization.JsonTransformation]
    public partial class TableDataProfile
    {
        /// <summary>
        /// Initializes a new instance of the TableDataProfile class.
        /// </summary>
        public TableDataProfile() { }

        /// <summary>
        /// Initializes a new instance of the TableDataProfile class.
        /// </summary>
        /// <param name="fromSourceSystem">fromSourceSystem property</param>
        /// <param name="key">key property</param>
        /// <param name="numberOfRows">numberOfRows property</param>
        /// <param name="size">size property</param>
        /// <param name="schemaModifiedTime">schemaModifiedTime
        /// property</param>
        /// <param name="dataModifiedTime">dataModifiedTime property</param>
        public TableDataProfile(bool fromSourceSystem, string key, long? numberOfRows = default(long?), long? size = default(long?), System.DateTime? schemaModifiedTime = default(System.DateTime?), System.DateTime? dataModifiedTime = default(System.DateTime?), System.Collections.Generic.IList<RolesItem> roles = default(System.Collections.Generic.IList<RolesItem>))
        {
            NumberOfRows = numberOfRows;
            Size = size;
            SchemaModifiedTime = schemaModifiedTime;
            DataModifiedTime = dataModifiedTime;
            FromSourceSystem = fromSourceSystem;
            Key = key;
            Roles = roles;
        }

        /// <summary>
        /// Gets or sets numberOfRows property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.numberOfRows")]
        public long? NumberOfRows { get; set; }

        /// <summary>
        /// Gets or sets size property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.size")]
        public long? Size { get; set; }

        /// <summary>
        /// Gets or sets schemaModifiedTime property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.schemaModifiedTime")]
        public System.DateTime? SchemaModifiedTime { get; set; }

        /// <summary>
        /// Gets or sets dataModifiedTime property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.dataModifiedTime")]
        public System.DateTime? DataModifiedTime { get; set; }

        /// <summary>
        /// Gets or sets fromSourceSystem property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.fromSourceSystem")]
        public bool FromSourceSystem { get; set; }

        /// <summary>
        /// Gets or sets key property
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "properties.key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "roles")]
        public System.Collections.Generic.IList<RolesItem> Roles { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Key == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Key");
            }
            if (this.Roles != null)
            {
                foreach (var element in this.Roles)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
